name: generative_ai_flutter
description: "Sample app for the google_generative_ai package"

publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_markdown: any
  # Note: best practice here is to use a caret version constraint. We use `any`
  # here just for the purpose of the sample.
  google_generative_ai: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Note: this section is only used in order to resolve google_generative_ai to
# the same repo as the sample.
dependency_overrides:
  google_generative_ai:
    path: ../../pkgs/google_generative_ai
